# travis config, based on https://github.com/craigcitro/r-travis

language: c
script: ./travis-tool.sh run_tests

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh aptget_install r-cran-rmpi 
  - ./travis-tool.sh github_package hadley/testthat
  - ./travis-tool.sh github_package hadley/assertthat
  - ./travis-tool.sh github_package berndbischl/BBmisc
  - ./travis-tool.sh github_package tudo-r/BatchJobs
  - ./travis-tool.sh github_package jimhester/covr
  - ./travis-tool.sh install_deps

branches:
  except:
   - /-expt$/

after_script:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
